FROM golang:latest

RUN apt-get update
RUN apt-get install vim -y
# Configure the repo url so we can configure our work directory:
ENV REPO_URL=github.com/anujmax/file-uploader

# Setup out $GOPATH
ENV GOPATH=/app

ENV APP_PATH=$GOPATH/src/$REPO_URL

ENV WORKPATH=$APP_PATH/src
COPY go.mod  $APP_PATH/
COPY go.sum  $APP_PATH/
COPY src $WORKPATH
WORKDIR $WORKPATH

RUN go build -o file-uploader .

EXPOSE 8080

CMD ["./file-uploader"]