version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_Mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: file_uploader
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: file_uploader_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: .
      dockerfile: Dockerfile_Go
    environment:
      AUTH_TOKEN: "my_app_token"
      MYSQL_ROOT_PASSWORD: root
      mysql_schema: file_uploader
      mysql_host: db
      mysql_username: root
      mysql_password: root
    container_name: file_uploader_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db